/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import java.net.InetAddress;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;

import chatsystem.Action;
import chatsystem.Contact;
import chatsystem.ContactList;
//import chatsystem.ContactsManager;
import ressources.Interfacedisplay;

/**
 *
 * @author Minh
 */
public class Connect extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Connect
     */

	private Action verify;
	
	private ContactList contactList;
	
	//Contacts Manager
//	private ContactsManager cm;
	
	//Main Page
	private MainMenu main;
	
    public Connect(String buttonText) {
    	this.setTitle(Interfacedisplay.connecttitle);
        initComponents();
        this.setLocationRelativeTo(null);
       
		contactList = new ContactList();
		
		// initialisation du contacts manager
//		cm = new ContactsManager(this);
//		cm.start();
		
		this.verify = new Action();
		
        jLabel1.setText("Username");

        buttonSubmit.setText(buttonText);
        buttonSubmit.setName("buttonSubmit");
        buttonSubmit.addActionListener(this.verify);

        enterPseudo.setName("enterPseudo");
        enterPseudo.addActionListener(this.verify);
        
        getRootPane().setDefaultButton(buttonSubmit);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	enterPseudo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText(Interfacedisplay.usernamelabel);

        buttonSubmit.setText(Interfacedisplay.connectbutton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(buttonSubmit)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(buttonSubmit)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // End of variables declaration//GEN-END:variables// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JTextField enterPseudo;
    // End of variables declaration//GEN-END:variables
	
    
    /////////////////////////////////////////////////////////////
    
    /*
     * Methods
     */
	public ContactList getContactList() {
		return contactList;
	}
	
	public static JTextField getEnterPseudo() {
		return enterPseudo;
	}

	public JFrame getConnectionFrame() {
		return this;
	}

	public JButton getbuttonSubmit() {
		return buttonSubmit;
	}

//	public ContactsManager getCm() {
//		return cm;
//	}
	
//	public void setCm(ContactsManager m) {
//		cm = m;
//	}

	public MainMenu getMain() {
		return main;
	}

	public void setMain(MainMenu main) {
		this.main = main;
	}
	
	public static void main(String[] args) {
		new Connect(Interfacedisplay.modifybutton);
		enterPseudo.setText("sdfds");
		System.out.println(enterPseudo.getText() == null);
	}
}
